"""empty message

Revision ID: 0538aa3b4580
Revises: 
Create Date: 2021-01-31 16:25:05.872723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0538aa3b4580'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('People')
    op.add_column('PromotionManager', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('PromotionManager', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('PromotionManager', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('PromotionManager', 'catchphrase')
    op.drop_column('PromotionManager', 'name')
    op.drop_column('PromotionManager', 'aditionaldata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PromotionManager', sa.Column('aditionaldata', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('PromotionManager', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('PromotionManager', sa.Column('catchphrase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('PromotionManager', 'phone_number')
    op.drop_column('PromotionManager', 'last_name')
    op.drop_column('PromotionManager', 'first_name')
    op.create_table('People',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"People_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('catchphrase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('aditionaldata', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='People_pkey')
    )
    # ### end Alembic commands ###
